package com.kuhen.cryptopro.data.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;

/**
 * JPA entity representing a generated trading signal.
 *
 * <p>Signals are generated by the strategy engine when market conditions align
 * with configured thresholds. Each signal captures the timeframe, direction,
 * and confidence score at the moment of generation.
 */
@Entity
@Table(
    name = "signals",
    indexes = {
        @Index(name = "idx_signals_instrument_time", columnList = "instrument_id, created_at DESC"),
        @Index(name = "idx_signals_type_time", columnList = "signal_type, created_at DESC")
    }
)
public class SignalEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "instrument_id", nullable = false)
    private Long instrumentId;

    @Column(name = "timeframe", nullable = false)
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    private TimeframeEnum timeframe;

    @Column(name = "signal_type", nullable = false)
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    private SignalTypeEnum signalType;

    @Column(name = "confidence_score", nullable = false)
    private Double confidenceScore;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Projected entry price computed at signal generation time (ATR-based). */
    @Column(name = "entry_price")
    private Double entryPrice;

    /** Projected stop-loss price computed at signal generation time (ATR-based). */
    @Column(name = "stop_loss")
    private Double stopLoss;

    /** Projected take-profit price computed at signal generation time (ATR-based). */
    @Column(name = "take_profit")
    private Double takeProfit;

    // Constructors
    public SignalEntity() {}

    public SignalEntity(Long instrumentId, TimeframeEnum timeframe,
                       SignalTypeEnum signalType, Double confidenceScore) {
        this.instrumentId = instrumentId;
        this.timeframe = timeframe;
        this.signalType = signalType;
        this.confidenceScore = confidenceScore;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInstrumentId() {
        return instrumentId;
    }

    public void setInstrumentId(Long instrumentId) {
        this.instrumentId = instrumentId;
    }

    public TimeframeEnum getTimeframe() {
        return timeframe;
    }

    public void setTimeframe(TimeframeEnum timeframe) {
        this.timeframe = timeframe;
    }

    public SignalTypeEnum getSignalType() {
        return signalType;
    }

    public void setSignalType(SignalTypeEnum signalType) {
        this.signalType = signalType;
    }

    public Double getConfidenceScore() {
        return confidenceScore;
    }

    public void setConfidenceScore(Double confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Double getEntryPrice() {
        return entryPrice;
    }

    public void setEntryPrice(Double entryPrice) {
        this.entryPrice = entryPrice;
    }

    public Double getStopLoss() {
        return stopLoss;
    }

    public void setStopLoss(Double stopLoss) {
        this.stopLoss = stopLoss;
    }

    public Double getTakeProfit() {
        return takeProfit;
    }

    public void setTakeProfit(Double takeProfit) {
        this.takeProfit = takeProfit;
    }

    @Override
    public String toString() {
        return "SignalEntity{" +
                "id=" + id +
                ", instrumentId=" + instrumentId +
                ", timeframe=" + timeframe +
                ", signalType=" + signalType +
                ", confidenceScore=" + confidenceScore +
                ", createdAt=" + createdAt +
                '}';
    }

    /**
     * Enum for timeframe types.
     */
    public enum TimeframeEnum {
        M1, M5, M15, H1
    }

    /**
     * Enum for signal types (direction).
     */
    public enum SignalTypeEnum {
        BUY, SELL
    }
}

